### ISSUE TITLE
It is possible to go straight using a keyboard

### ISSUE THREAD

**Issue by Porrumentzio** [lufte/lona#21]
If a key is kept pressed, lona can go straight instead of curvy. Maybe this is not wanted or maybe could be a secret/easter egg

The solution to avoid this could be to disallow interpreting key-signals if they are kept pressed.

**Comment by lufte** [comment]
Hmm, you are right, but it doesn't look so easy to master. Specially because Lona turns the other way as soon as you press the key, then takes some time before going straight (because of the "delay until repeat" setting of your OS), and finally you don't really know which way she will go after releasing the key. 

I don't think it's much of an advantage really, and you can achieve something similar by pressing the key or tapping the screen really fast. Thanks for the tip though :D
