### ISSUE TITLE
Feature Request: Game Modi

### ISSUE THREAD

**Issue by ApoRes1337** [lufte/lona#6]
Hello Javier,

I wanted to ask if it would be conceivable for you to implement the "Standard Snake" game as a secondary game mode.

Yesterday I shared the link to the game in the Fediverse and some users would also like the game with the classic mode.

Greetz Christopher from Germany,
if you need help for Translating this Game in German call me. :)

**Comment by lufte** [comment]
Hi Greetz. 

To be honest, this is just a game I wrote quite long ago which I now considered "done" and just wanted to publish it somewhere (since it used to be published in the Firefox marketplace but that died). 

I wouldn't mind fixing some bugs should there be any, but what you're asking is really to write a different game, and I'm sure there are lots of classical snake games out there. I hope you understand.

To help with translation you simply need to expand the locales.ini file with your language and send me a pull request.

I'm glad you liked my game. Feel free to fork it if you decide to write a classical snake version of it yourself. Cheers 😊
